### ISSUE TITLE
扩展的设置页面入口在哪？

### ISSUE THREAD

**Issue by qianmianyao** [L018/Trace#2]
好像没有看到设置页面的入口

**Comment by L018** [comment]
安装完成后，鼠标右键单击图标，点击`Options`即可弹出设置页面。（鼠标左键单击图标为`Popup`页）
<img width="249" alt="option" src="https://user-images.githubusercontent.com/35761189/236272622-a73143e3-833a-4b3a-a475-f98afb5490cf.png">
